name: IoT Schedule Job

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      delay_minutes:
        description: 'Delay in minutes before running the job'
        required: true
        default: '5'

jobs:
  delay_job:
    runs-on: ubuntu-latest
    steps:
      - name: Job scheduled...
        id: schedule
        run: |
          echo "Triggered time: `date`."
          #convert to seconds and save to GITHUB_OUTPUT
          delay=$((${{ github.event.inputs.delay_minutes }} * 60))
          echo "delay=$delay" >> $GITHUB_OUTPUT
          echo "delay in seconds: $delay"
          sleep $delay

      - name: Trigger scheduled job
        run: |
          echo "The scheduled job is running after ${{ github.event.inputs.delay_minutes }} minutes delay at: `date`."