name: IoT Schedule Job

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      delay_minutes:
        description: 'Delay in minutes before running the job'
        required: true
        default: '5'

jobs:
  delay_job:
    runs-on: ubuntu-latest
    steps:
      - name: Job scheduled...
        id: schedule
        run: |
          echo "Triggered time: `date`."
          #convert to seconds and save to GITHUB_OUTPUT
          delay=$((${{ github.event.inputs.delay_minutes }} * 60))
          echo "delay=$delay" >> $GITHUB_OUTPUT
          echo "delay in seconds: $delay"
          sleep $delay

      - name: Trigger scheduled job
        run: |
          echo "Scheduled job is triggered after ${{ github.event.inputs.delay_minutes }} minutes delay at: `date`."

  job_action:
    runs-on: ubuntu-latest
    needs: ["delay_job"]
    steps:
      - name: Get ChatGPT completion
        id: chatgpt
        uses: cahaseler/openai-api@v1
        with:
          apiKey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'Please generate a movie suggestion list (list should contain at least 8) for english and telugu language each, for following genres'
          input: 'Action, Comedy'
          model: 'gpt-3.5-turbo'
          temperature: 0.3
          max_tokens: 300