name: IoT Schedule Job

permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      delay_minutes:
        description: 'Delay in minutes before running the job'
        required: true
        default: '5'

jobs:
  delay_job:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate Delay
        id: calculate
        run: |
          echo "Triggered time: `date`"
          echo "$((${{ github.event.inputs.delay_minutes }} * 60))"
          echo "delay=$((${{ github.event.inputs.delay_minutes }} * 60))" >> $GITHUB_OUTPUT
          echo "$GITHUB_OUTPUT"

      - name: Job Waiting..
        run: |
          sleep ${{ steps.calculate.outputs.delay }}

      - name: Trigger Scheduled Job
        run: |
          echo "The scheduled job is running after ${{ github.event.inputs.delay_minutes }} minutes delay."
          echo "at: `date` "